CREATE DATABASE IF NOT EXISTS todos;
use todos;
CREATE TABLE IF NOT EXISTS plan (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `description` VARCHAR(255),
    `done` BOOLEAN NOT NULL,
    `targetDay` DATETIME NOT NULL,
    `created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_date` DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP,
	`created_user` varchar(255) NOT NULL,
	`updated_user` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB;